name: 📧 Notify on data.json Update

on:
  push:
    paths:
      - 'data.json'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email via SendGrid
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: "data.json was updated!"
          to: nkchaudhary431@gmail.com
          from: ce22b080@smail.iitm.ac.in
          body: |
            Hi there,
      
            This is an automated message from the 7pi_data repo.
            The file `data.json` has been updated.

            📄 View the file here:
            https://ziptripp.github.io/7pi_data/data.json
