name: 📧 Notify on data.json Update

on:
  push:
    paths:
      - 'data.json'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email via SendGrid
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: "✅ data.json was updated!"
          to: nirwairkumar1@gmail.com
          from: learnirwair@gmail.com
          body: |
            The file **data.json** has been updated in the [7pi_data repo](https://github.com/ZipTripp/7pi_data).
            View live data here: https://ziptripp.github.io/7pi_data/data.json
